export const musicData = [
  /**
   * 2010-2019 SONGS
   * Tempo - Beats per minute
   * Energy - The higher the value, the more energetic the song is
   * Danceability - The higher the value, the easier it is to dance to the song.
   * Reference: https://www.kaggle.com/datasets/leonardopena/top-spotify-songs-from-20102019-by-year
   */
  {
    title: "Hey, Soul Sister",
    artist: "Train",
    genre: "Neo Mellow",
    features: [97, 89, 67],
  },
  {
    title: "Love The Way You Lie",
    artist: "Eminem",
    genre: "Detroit Hip Hop",
    features: [87, 93, 75],
  },
  {
    title: "TiK ToK",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [120, 84, 76],
  },
  {
    title: "Bad Romance",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [119, 92, 70],
  },
  {
    title: "Just the Way You Are",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [109, 84, 64],
  },
  {
    title: "Baby",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [65, 86, 73],
  },
  {
    title: "Dynamite",
    artist: "Taio Cruz",
    genre: "Dance Pop",
    features: [120, 78, 75],
  },
  {
    title: "Secrets",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [148, 76, 52],
  },
  {
    title: "Empire State of Mind (Part II) Broken Down",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [93, 37, 48],
  },
  {
    title: "Only Girl (In The World)",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [126, 72, 79],
  },
  {
    title: "Club Can't Handle Me (feat. David Guetta)",
    artist: "Flo Rida",
    genre: "Dance Pop",
    features: [128, 87, 62],
  },
  {
    title: "Marry You",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [145, 83, 62],
  },
  {
    title: "Cooler Than Me - Single Mix",
    artist: "Mike Posner",
    genre: "Dance Pop",
    features: [130, 82, 77],
  },
  {
    title: "Telephone",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [122, 83, 83],
  },
  {
    title: "Like A G6",
    artist: "Far East Movement",
    genre: "Dance Pop",
    features: [125, 84, 44],
  },
  {
    title: "OMG (feat. will.i.am)",
    artist: "Usher",
    genre: "Atl Hip Hop",
    features: [130, 75, 78],
  },
  {
    title: "Eenie Meenie",
    artist: "Sean Kingston",
    genre: "Dance Pop",
    features: [121, 61, 72],
  },
  {
    title: "The Time (Dirty Bit)",
    artist: "The Black Eyed Peas",
    genre: "Dance Pop",
    features: [128, 81, 82],
  },
  {
    title: "Alejandro",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [99, 80, 63],
  },
  {
    title: "Your Love Is My Drug",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [120, 61, 83],
  },
  {
    title: "Meet Me Halfway",
    artist: "The Black Eyed Peas",
    genre: "Dance Pop",
    features: [130, 63, 80],
  },
  {
    title: "Whataya Want from Me",
    artist: "Adam Lambert",
    genre: "Australian Pop",
    features: [186, 68, 44],
  },
  {
    title: "Take It Off",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [125, 68, 73],
  },
  {
    title: "Misery",
    artist: "Maroon 5",
    genre: "Pop",
    features: [103, 81, 70],
  },
  {
    title: "All The Right Moves",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [146, 95, 53],
  },
  {
    title: "Animal",
    artist: "Neon Trees",
    genre: "Indie Pop",
    features: [148, 83, 48],
  },
  {
    title: "Naturally",
    artist: "Selena Gomez & The Scene",
    genre: "Dance Pop",
    features: [133, 90, 61],
  },
  {
    title: "I Like It",
    artist: "Enrique Iglesias",
    genre: "Dance Pop",
    features: [129, 94, 65],
  },
  {
    title: "Teenage Dream",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [120, 80, 72],
  },
  {
    title: "California Gurls",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [125, 75, 79],
  },
  {
    title: "3",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [135, 71, 70],
  },
  {
    title: "My First Kiss - feat. Ke$ha",
    artist: "3OH!3",
    genre: "Dance Pop",
    features: [138, 89, 68],
  },
  {
    title: "Blah Blah Blah (feat. 3OH!3)",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [120, 84, 75],
  },
  {
    title: "Imma Be",
    artist: "The Black Eyed Peas",
    genre: "Dance Pop",
    features: [92, 52, 60],
  },
  {
    title: "Try Sleeping with a Broken Heart",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [111, 82, 50],
  },
  {
    title: "Sexy Bitch (feat. Akon)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [130, 63, 81],
  },
  {
    title: "Bound To You - Burlesque Original Motion Picture Soundtrack",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [164, 41, 29],
  },
  {
    title: "If I Had You",
    artist: "Adam Lambert",
    genre: "Australian Pop",
    features: [131, 91, 65],
  },
  {
    title: "Rock That Body",
    artist: "The Black Eyed Peas",
    genre: "Dance Pop",
    features: [125, 91, 72],
  },
  {
    title: "Dog Days Are Over",
    artist: "Florence + The Machine",
    genre: "Art Pop",
    features: [150, 81, 50],
  },
  {
    title:
      "Something's Got A Hold On Me - Burlesque Original Motion Picture Soundtrack",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [150, 85, 51],
  },
  {
    title: "Doesn't Mean Anything",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [104, 41, 71],
  },
  {
    title: "Hard",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [182, 75, 31],
  },
  {
    title: "Loca",
    artist: "Shakira",
    genre: "Colombian Pop",
    features: [112, 87, 80],
  },
  {
    title: "You Lost Me",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [43, 39, 23],
  },
  {
    title: "Not Myself Tonight",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [120, 81, 76],
  },
  {
    title: "Written in the Stars (feat. Eric Turner)",
    artist: "Tinie Tempah",
    genre: "Dance Pop",
    features: [91, 95, 64],
  },
  {
    title: "DJ Got Us Fallin' In Love (feat. Pitbull)",
    artist: "Usher",
    genre: "Atl Hip Hop",
    features: [120, 86, 66],
  },
  {
    title: "Castle Walls (feat. Christina Aguilera)",
    artist: "T.I.",
    genre: "Atl Hip Hop",
    features: [80, 86, 45],
  },
  {
    title: "Break Your Heart",
    artist: "Taio Cruz",
    genre: "Dance Pop",
    features: [122, 90, 67],
  },
  {
    title: "Hello",
    artist: "Martin Solveig",
    genre: "Big Room",
    features: [128, 98, 67],
  },
  {
    title: "A Thousand Years",
    artist: "Christina Perri",
    genre: "Dance Pop",
    features: [139, 41, 42],
  },
  {
    title: "Someone Like You",
    artist: "Adele",
    genre: "British Soul",
    features: [135, 33, 56],
  },
  {
    title: "Give Me Everything",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [129, 94, 67],
  },
  {
    title: "Just the Way You Are",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [109, 84, 64],
  },
  {
    title: "Rolling in the Deep",
    artist: "Adele",
    genre: "British Soul",
    features: [105, 76, 73],
  },
  {
    title: "Run the World (Girls)",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [127, 90, 73],
  },
  {
    title: "Moves Like Jagger - Studio Recording From The Voice Performance",
    artist: "Maroon 5",
    genre: "Pop",
    features: [128, 76, 72],
  },
  {
    title: "Love On Top",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [94, 75, 65],
  },
  {
    title: "Grenade",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [110, 56, 71],
  },
  {
    title: "Tonight Tonight",
    artist: "Hot Chelle Rae",
    genre: "Dance Pop",
    features: [100, 78, 69],
  },
  {
    title: "What the Hell",
    artist: "Avril Lavigne",
    genre: "Canadian Pop",
    features: [150, 93, 58],
  },
  {
    title: "Born This Way",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [124, 83, 59],
  },
  {
    title: "Monster",
    artist: "Kanye West",
    genre: "Chicago Rap",
    features: [125, 69, 63],
  },
  {
    title: "Marry You",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [145, 83, 62],
  },
  {
    title: "Best Thing I Never Had",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [99, 65, 55],
  },
  {
    title: "Party Rock Anthem",
    artist: "LMFAO",
    genre: "Dance Pop",
    features: [130, 74, 75],
  },
  {
    title: "We R Who We R",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [120, 82, 74],
  },
  {
    title: "Price Tag",
    artist: "Jessie J",
    genre: "Australian Pop",
    features: [175, 83, 64],
  },
  {
    title: "Good Life",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [95, 69, 63],
  },
  {
    title: "Just Can抰 Get Enough",
    artist: "The Black Eyed Peas",
    genre: "Dance Pop",
    features: [94, 63, 66],
  },
  {
    title: "On The Floor",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [130, 78, 73],
  },
  {
    title: "What's My Name?",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [100, 79, 69],
  },
  {
    title: "Yeah 3x",
    artist: "Chris Brown",
    genre: "Dance Pop",
    features: [130, 88, 71],
  },
  {
    title: "Without You (feat. Usher)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [128, 61, 61],
  },
  {
    title: "Sexy And I Know It",
    artist: "LMFAO",
    genre: "Dance Pop",
    features: [130, 86, 71],
  },
  {
    title: "The Edge Of Glory",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [128, 77, 58],
  },
  {
    title: "E.T.",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [152, 87, 62],
  },
  {
    title: "Till the World Ends",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [132, 71, 69],
  },
  {
    title: "I Wanna Go",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [130, 55, 70],
  },
  {
    title: "Blow",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [120, 73, 75],
  },
  {
    title: "You And I",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [127, 70, 52],
  },
  {
    title: "Judas",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [131, 93, 66],
  },
  {
    title: "Tonight (I'm Fuckin' You)",
    artist: "Enrique Iglesias",
    genre: "Dance Pop",
    features: [126, 89, 65],
  },
  {
    title: "Please Don't Go",
    artist: "Mike Posner",
    genre: "Dance Pop",
    features: [120, 88, 70],
  },
  {
    title: "We Found Love",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [128, 77, 73],
  },
  {
    title: "Marry The Night",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [131, 88, 61],
  },
  {
    title: "1+1",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [63, 38, 30],
  },
  {
    title: "Hold It Against Me",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [133, 72, 65],
  },
  {
    title: "I'm Into You",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [84, 75, 59],
  },
  {
    title: "Papi",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [120, 81, 71],
  },
  {
    title: "Cheers (Drink To That)",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [80, 91, 58],
  },
  {
    title: "S&M Remix",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [128, 81, 82],
  },
  {
    title: "Written in the Stars (feat. Eric Turner)",
    artist: "Tinie Tempah",
    genre: "Dance Pop",
    features: [91, 95, 64],
  },
  {
    title: "Jar of Hearts",
    artist: "Christina Perri",
    genre: "Dance Pop",
    features: [75, 35, 35],
  },
  {
    title: "Castle Walls (feat. Christina Aguilera)",
    artist: "T.I.",
    genre: "Atl Hip Hop",
    features: [80, 86, 45],
  },
  {
    title: "Turning Page",
    artist: "Sleeping At Last",
    genre: "Acoustic Pop",
    features: [125, 38, 30],
  },
  {
    title: "Super Bass",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [127, 74, 77],
  },
  {
    title: "Raise Your Glass",
    artist: "P!nk",
    genre: "Dance Pop",
    features: [122, 64, 68],
  },
  {
    title: "Invading My Mind",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [129, 88, 73],
  },
  {
    title: "Moment 4 Life - Album Version (Edited)",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [130, 88, 50],
  },
  {
    title: "Last Friday Night (T.G.I.F.)",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [126, 81, 65],
  },
  {
    title: "Firework",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [124, 83, 64],
  },
  {
    title: "Muny - Album Version (Edited)",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [98, 72, 80],
  },
  {
    title: "Titanium (feat. Sia)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [126, 79, 60],
  },
  {
    title: "Locked Out of Heaven",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [144, 70, 73],
  },
  {
    title: "Paradise",
    artist: "Coldplay",
    genre: "permanent wave",
    features: [140, 59, 45],
  },
  {
    title: "Payphone",
    artist: "Maroon 5",
    genre: "Pop",
    features: [110, 75, 74],
  },
  {
    title: "What Makes You Beautiful",
    artist: "One Direction",
    genre: "Boy Band",
    features: [125, 79, 73],
  },
  {
    title: "I Knew You Were Trouble.",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [77, 47, 62],
  },
  {
    title: "Call Me Maybe",
    artist: "Carly Rae Jepsen",
    genre: "Canadian Pop",
    features: [120, 58, 78],
  },
  {
    title: "Love You Like A Love Song",
    artist: "Selena Gomez & The Scene",
    genre: "Dance Pop",
    features: [117, 68, 86],
  },
  {
    title: "Set Fire to the Rain",
    artist: "Adele",
    genre: "British Soul",
    features: [108, 68, 61],
  },
  {
    title: "We Are Never Ever Getting Back Together",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [86, 68, 63],
  },
  {
    title: "Stronger (What Doesn't Kill You)",
    artist: "Kelly Clarkson",
    genre: "Dance Pop",
    features: [116, 94, 56],
  },
  {
    title: "Try",
    artist: "P!nk",
    genre: "Dance Pop",
    features: [104, 63, 67],
  },
  {
    title: "Starships",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [125, 72, 75],
  },
  {
    title: "One More Night",
    artist: "Maroon 5",
    genre: "Pop",
    features: [93, 82, 72],
  },
  {
    title: "Good Time",
    artist: "Owl City",
    genre: "Pop",
    features: [126, 87, 56],
  },
  {
    title: "Glad You Came",
    artist: "The Wanted",
    genre: "Boy Band",
    features: [127, 85, 72],
  },
  {
    title: "Beauty And A Beat",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [128, 84, 60],
  },
  {
    title: "International Love",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [120, 86, 67],
  },
  {
    title: "Some Nights",
    artist: "fun.",
    genre: "baroque Pop",
    features: [108, 74, 67],
  },
  {
    title: "Boyfriend",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [97, 55, 72],
  },
  {
    title: "Part Of Me",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [130, 92, 68],
  },
  {
    title: "Domino",
    artist: "Jessie J",
    genre: "Australian Pop",
    features: [127, 55, 76],
  },
  {
    title: "Where Have You Been",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [128, 85, 72],
  },
  {
    title: "Wide Awake",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [160, 68, 51],
  },
  {
    title: "The One That Got Away",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [134, 80, 69],
  },
  {
    title: "Dance Again",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [128, 86, 79],
  },
  {
    title: "Turn Up the Music",
    artist: "Chris Brown",
    genre: "Dance Pop",
    features: [130, 84, 59],
  },
  {
    title: "Lights - Single Version",
    artist: "Ellie Goulding",
    genre: "Dance Pop",
    features: [120, 80, 68],
  },
  {
    title: "We Are Young (feat. Janelle Mon醗)",
    artist: "fun.",
    genre: "baroque Pop",
    features: [184, 64, 38],
  },
  {
    title: "Diamonds",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [92, 71, 56],
  },
  {
    title: "Don't Stop the Party (feat. TJR)",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [127, 96, 72],
  },
  {
    title: "You Da One",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [127, 72, 70],
  },
  {
    title: "Stereo Hearts (feat. Adam Levine)",
    artist: "Gym Class Heroes",
    genre: "Dance Pop",
    features: [90, 80, 65],
  },
  {
    title: "It Will Rain",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [150, 84, 58],
  },
  {
    title: "Blow Me (One Last Kiss)",
    artist: "P!nk",
    genre: "Dance Pop",
    features: [114, 92, 60],
  },
  {
    title: "Underneath the Tree",
    artist: "Kelly Clarkson",
    genre: "Dance Pop",
    features: [160, 81, 51],
  },
  {
    title: "Wake Me Up",
    artist: "Avicii",
    genre: "Big Room",
    features: [124, 78, 53],
  },
  {
    title: "Story of My Life",
    artist: "One Direction",
    genre: "Boy Band",
    features: [121, 66, 60],
  },
  {
    title: "Just Give Me a Reason (feat. Nate Ruess)",
    artist: "P!nk",
    genre: "Dance Pop",
    features: [95, 55, 78],
  },
  {
    title: "Hall of Fame",
    artist: "The Script",
    genre: "celtic rock",
    features: [85, 87, 42],
  },
  {
    title: "Roar",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [180, 77, 55],
  },
  {
    title: "We Can't Stop",
    artist: "Miley Cyrus",
    genre: "Dance Pop",
    features: [80, 62, 61],
  },
  {
    title: "Don't You Worry Child - Radio Edit",
    artist: "Swedish House Mafia",
    genre: "Big Room",
    features: [129, 84, 61],
  },
  {
    title: "Get Lucky (feat. Pharrell Williams & Nile Rodgers) - Radio Edit",
    artist: "Daft Punk",
    genre: "Electro",
    features: [116, 81, 79],
  },
  {
    title: "Wrecking Ball",
    artist: "Miley Cyrus",
    genre: "Dance Pop",
    features: [120, 42, 53],
  },
  {
    title: "Impossible",
    artist: "James Arthur",
    genre: "Pop",
    features: [170, 70, 38],
  },
  {
    title: "Blurred Lines",
    artist: "Robin Thicke",
    genre: "Dance Pop",
    features: [120, 60, 85],
  },
  {
    title: "Heart Attack",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [174, 79, 50],
  },
  {
    title: "We Are Never Ever Getting Back Together",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [86, 68, 63],
  },
  {
    title: "Die Young",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [128, 70, 71],
  },
  {
    title: "Clarity",
    artist: "Zedd",
    genre: "Complextro",
    features: [128, 78, 51],
  },
  {
    title:
      "Summertime Sadness (Lana Del Rey Vs. Cedric Gervais) - Cedric Gervais Remix",
    artist: "Lana Del Rey",
    genre: "Art Pop",
    features: [126, 81, 57],
  },
  {
    title: "Under Control",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [126, 92, 54],
  },
  {
    title: "Everybody Talks",
    artist: "Neon Trees",
    genre: "Indie Pop",
    features: [155, 92, 47],
  },
  {
    title: '"Hold On',
    artist: " We're Going Home\"",
    genre: "Drake",
    features: [null, 100, 41],
  },
  {
    title: "Best Song Ever",
    artist: "One Direction",
    genre: "Boy Band",
    features: [118, 88, 65],
  },
  {
    title: "Kiss You",
    artist: "One Direction",
    genre: "Boy Band",
    features: [90, 93, 63],
  },
  {
    title: "Sweet Nothing (feat. Florence Welch)",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [128, 93, 57],
  },
  {
    title: "Lose Yourself to Dance",
    artist: "Daft Punk",
    genre: "Electro",
    features: [100, 66, 83],
  },
  {
    title: "Work Bitch",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [128, 82, 63],
  },
  {
    title: "Brave",
    artist: "Sara Bareilles",
    genre: "Acoustic Pop",
    features: [185, 84, 55],
  },
  {
    title: "Can't Hold Us (feat. Ray Dalton)",
    artist: "Macklemore & Ryan Lewis",
    genre: "Dance Pop",
    features: [146, 93, 63],
  },
  {
    title: "Feel This Moment (feat. Christina Aguilera)",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [136, 76, 67],
  },
  {
    title: "Beneath Your Beautiful",
    artist: "Labrinth",
    genre: "Pop",
    features: [84, 52, 56],
  },
  {
    title: "Let Me Love You (Until You Learn To Love Yourself)",
    artist: "Ne-Yo",
    genre: "Dance Pop",
    features: [125, 68, 66],
  },
  {
    title: "Thrift Shop (feat. Wanz)",
    artist: "Macklemore & Ryan Lewis",
    genre: "Dance Pop",
    features: [95, 53, 78],
  },
  {
    title: "If I Lose Myself - Alesso vs OneRepublic",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [126, 75, 52],
  },
  {
    title: "The Way",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [82, 88, 65],
  },
  {
    title: "Suit & Tie",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [102, 60, 80],
  },
  {
    title: "#thatPOWER",
    artist: "will.i.am",
    genre: "Dance Pop",
    features: [128, 61, 80],
  },
  {
    title: "I Love It (feat. Charli XCX)",
    artist: "Icona Pop",
    genre: "candy Pop",
    features: [126, 91, 71],
  },
  {
    title: "Play Hard (feat. Ne-Yo & Akon) - New Edit",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [130, 87, 72],
  },
  {
    title: "Daylight",
    artist: "Maroon 5",
    genre: "Pop",
    features: [120, 67, 66],
  },
  {
    title: "Love Somebody",
    artist: "Maroon 5",
    genre: "Pop",
    features: [120, 78, 68],
  },
  {
    title: "A Little Party Never Killed Nobody (All We Got)",
    artist: "Fergie",
    genre: "Dance Pop",
    features: [130, 62, 76],
  },
  {
    title: "Move",
    artist: "Little Mix",
    genre: "Dance Pop",
    features: [121, 74, 85],
  },
  {
    title: "Walks Like Rihanna",
    artist: "The Wanted",
    genre: "Boy Band",
    features: [126, 82, 56],
  },
  {
    title: "Rock N Roll",
    artist: "Avril Lavigne",
    genre: "Canadian Pop",
    features: [184, 96, 47],
  },
  {
    title: "Heartbreaker",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [105, 52, 56],
  },
  {
    title: "Mirrors - Radio Edit",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [77, 60, 58],
  },
  {
    title: "Next To Me",
    artist: "Emeli Sande",
    genre: "Dance Pop",
    features: [95, 80, 67],
  },
  {
    title: "Made In The USA",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [87, 86, 58],
  },
  {
    title: "Clown",
    artist: "Emeli Sande",
    genre: "Dance Pop",
    features: [130, 23, 45],
  },
  {
    title: "Girl On Fire (feat. Nicki Minaj) - Inferno Version",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [93, 81, 55],
  },
  {
    title: "TKO",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [138, 68, 61],
  },
  {
    title: "Come & Get It",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [80, 79, 55],
  },
  {
    title: "Live It Up",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [128, 73, 69],
  },
  {
    title: "We Own The Night",
    artist: "The Wanted",
    genre: "Boy Band",
    features: [104, 94, 55],
  },
  {
    title: "Atlas - From 揟he Hunger Games: Catching Fire?Soundtrack",
    artist: "Coldplay",
    genre: "permanent wave",
    features: [136, 45, 28],
  },
  {
    title: "What About Love",
    artist: "Austin Mahone",
    genre: "Dance Pop",
    features: [100, 78, 63],
  },
  {
    title: "Take Back the Night",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [107, 66, 59],
  },
  {
    title: "Applause",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [140, 78, 67],
  },
  {
    title: "Anything Could Happen",
    artist: "Ellie Goulding",
    genre: "Dance Pop",
    features: [103, 78, 70],
  },
  {
    title: "Finally Found You",
    artist: "Enrique Iglesias",
    genre: "Dance Pop",
    features: [128, 88, 62],
  },
  {
    title: "Pom Poms",
    artist: "Jonas Brothers",
    genre: "Boy Band",
    features: [148, 98, 68],
  },
  {
    title: "#Beautiful",
    artist: "Mariah Carey",
    genre: "Dance Pop",
    features: [107, 76, 68],
  },
  {
    title: "How Ya Doin'? (feat. Missy Elliott)",
    artist: "Little Mix",
    genre: "Dance Pop",
    features: [201, 95, 36],
  },
  {
    title: "Crazy Kids (feat. will.i.am)",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [128, 75, 72],
  },
  {
    title: '"Ooh La La (from ""The Smurfs 2"")"',
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [128, 57, 69],
  },
  {
    title: "People Like Us",
    artist: "Kelly Clarkson",
    genre: "Dance Pop",
    features: [128, 79, 60],
  },
  {
    title: "Overdose",
    artist: "Ciara",
    genre: "Dance Pop",
    features: [107, 70, 77],
  },
  {
    title: "Right Now - Dyro Radio Edit",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [130, 74, 53],
  },
  {
    title: "Give It 2 U",
    artist: "Robin Thicke",
    genre: "Dance Pop",
    features: [127, 83, 67],
  },
  {
    title: "Foolish Games",
    artist: "Jewel",
    genre: "Alaska Indie",
    features: [132, 34, 51],
  },
  {
    title: "Outta Nowhere (feat. Danny Mercer)",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [95, 84, 71],
  },
  {
    title: "Freak",
    artist: "Kelly Rowland",
    genre: "Atl Hip Hop",
    features: [104, 78, 65],
  },
  {
    title: "All of Me",
    artist: "John Legend",
    genre: "Neo Mellow",
    features: [120, 26, 42],
  },
  {
    title: "Stay With Me",
    artist: "Sam Smith",
    genre: "Pop",
    features: [84, 42, 42],
  },
  {
    title: "Summer",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [128, 86, 60],
  },
  {
    title: '"Happy - From ""Despicable Me 2"""',
    artist: "Pharrell Williams",
    genre: "Dance Pop",
    features: [160, 82, 65],
  },
  {
    title: "Rude",
    artist: "MAGIC!",
    genre: "Pop",
    features: [144, 76, 77],
  },
  {
    title: "Shake It Off",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [160, 80, 65],
  },
  {
    title: "Dark Horse",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [132, 59, 65],
  },
  {
    title: "Hey Brother",
    artist: "Avicii",
    genre: "Big Room",
    features: [125, 78, 55],
  },
  {
    title: "Maps",
    artist: "Maroon 5",
    genre: "Pop",
    features: [120, 71, 74],
  },
  {
    title: "Treasure",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [116, 69, 87],
  },
  {
    title: "Let Her Go",
    artist: "Passenger",
    genre: "Folk-Pop",
    features: [75, 54, 51],
  },
  {
    title: "Problem",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [103, 81, 66],
  },
  {
    title: "Pompeii",
    artist: "Bastille",
    genre: "Metropopolis",
    features: [127, 72, 68],
  },
  {
    title: "Team",
    artist: "Lorde",
    genre: "Art Pop",
    features: [100, 58, 69],
  },
  {
    title: "Love Me Again",
    artist: "John Newman",
    genre: "Pop",
    features: [126, 89, 50],
  },
  {
    title: "Latch",
    artist: "Disclosure",
    genre: "house",
    features: [122, 73, 50],
  },
  {
    title: "Adore You",
    artist: "Miley Cyrus",
    genre: "Dance Pop",
    features: [120, 66, 58],
  },
  {
    title: "Love Never Felt So Good",
    artist: "Michael Jackson",
    genre: "Pop",
    features: [118, 72, 78],
  },
  {
    title: "Burn",
    artist: "Ellie Goulding",
    genre: "Dance Pop",
    features: [87, 78, 56],
  },
  {
    title: "She Looks So Perfect",
    artist: "5 Seconds of Summer",
    genre: "Boy Band",
    features: [160, 95, 49],
  },
  {
    title: "Fancy",
    artist: "Iggy Azalea",
    genre: "Australian Hip Hop",
    features: [95, 72, 91],
  },
  {
    title: "Talk Dirty (feat. 2 Chainz)",
    artist: "Jason Derulo",
    genre: "Dance Pop",
    features: [100, 65, 76],
  },
  {
    title: "Gorilla",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [140, 54, 72],
  },
  {
    title: "human",
    artist: "Christina Perri",
    genre: "Dance Pop",
    features: [144, 49, 44],
  },
  {
    title: "Young Girls",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [126, 75, 56],
  },
  {
    title: "Wiggle (feat. Snoop Dogg)",
    artist: "Jason Derulo",
    genre: "Dance Pop",
    features: [82, 62, 70],
  },
  {
    title: "Love Runs Out",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [120, 93, 72],
  },
  {
    title: "This Is How We Do",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [96, 64, 69],
  },
  {
    title: "Mmm Yeah (feat. Pitbull)",
    artist: "Austin Mahone",
    genre: "Dance Pop",
    features: [126, 92, 71],
  },
  {
    title: "A Little Party Never Killed Nobody (All We Got)",
    artist: "Fergie",
    genre: "Dance Pop",
    features: [130, 62, 76],
  },
  {
    title: "#SELFIE",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [128, 92, 79],
  },
  {
    title: "Partition",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [186, 44, 41],
  },
  {
    title: "Birthday",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [126, 67, 72],
  },
  {
    title: "G.U.Y.",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [110, 92, 62],
  },
  {
    title: "Stay The Night - Featuring Hayley Williams Of Paramore",
    artist: "Zedd",
    genre: "Complextro",
    features: [128, 74, 60],
  },
  {
    title: '"Let It Go - From ""Frozen / Single Version"',
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [140, 66, 50],
  },
  {
    title: "Wings",
    artist: "Birdy",
    genre: "Neo Mellow",
    features: [83, 71, 47],
  },
  {
    title: "Can't Remember to Forget You (feat. Rihanna)",
    artist: "Shakira",
    genre: "Colombian Pop",
    features: [138, 81, 69],
  },
  {
    title: "Shot Me Down (feat. Skylar Grey) - Radio Edit",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [192, 77, 35],
  },
  {
    title: "Say Something",
    artist: "A Great Big World",
    genre: "Neo Mellow",
    features: [138, 15, 45],
  },
  {
    title: "A Sky Full of Stars",
    artist: "Coldplay",
    genre: "permanent wave",
    features: [125, 68, 55],
  },
  {
    title: "Come Get It Bae",
    artist: "Pharrell Williams",
    genre: "Dance Pop",
    features: [120, 80, 93],
  },
  {
    title: "Chandelier",
    artist: "Sia",
    genre: "Australian dance",
    features: [174, 78, 29],
  },
  {
    title: "XO",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [170, 79, 47],
  },
  {
    title: "We Are One (Ole Ola) [The Official 2014 FIFA World Cup Song]",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [125, 94, 60],
  },
  {
    title: "Not About Angels",
    artist: "Birdy",
    genre: "Neo Mellow",
    features: [116, 14, 41],
  },
  {
    title: "Drunk in Love",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [140, 62, 59],
  },
  {
    title: "Anaconda",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [130, 60, 96],
  },
  {
    title:
      "Boom Clap - From the Motion Picture Das Schicksal ist ein mieser Verr鋞er",
    artist: "Charli XCX",
    genre: "candy Pop",
    features: [92, 81, 68],
  },
  {
    title: "La La La (Brasil 2014) (feat. Carlinhos Brown)",
    artist: "Shakira",
    genre: "Colombian Pop",
    features: [128, 82, 80],
  },
  {
    title: "Tee Shirt - Soundtrack Version",
    artist: "Birdy",
    genre: "Neo Mellow",
    features: [76, 34, 68],
  },
  {
    title: "Words as Weapons",
    artist: "Birdy",
    genre: "Neo Mellow",
    features: [120, 35, 53],
  },
  {
    title: "You're Mine (Eternal)",
    artist: "Mariah Carey",
    genre: "Dance Pop",
    features: [149, 58, 63],
  },
  {
    title: "Sheezus",
    artist: "Lily Allen",
    genre: "Dance Pop",
    features: [130, 50, 78],
  },
  {
    title: "Cannonball",
    artist: "Lea Michele",
    genre: "hollywood",
    features: [92, 82, 56],
  },
  {
    title: "It's On Again - Main Soundtrack",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [110, 54, 64],
  },
  {
    title: "I Luh Ya Papi",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [96, 73, 74],
  },
  {
    title: "Not a Bad Thing",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [86, 73, 59],
  },
  {
    title: "Thinking out Loud",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [79, 45, 78],
  },
  {
    title: "I'm Not The Only One",
    artist: "Sam Smith",
    genre: "Pop",
    features: [82, 49, 68],
  },
  {
    title: "The Hills",
    artist: "The Weeknd",
    genre: "Canadian Contemporary R&B",
    features: [113, 56, 58],
  },
  {
    title: "Love Yourself",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [100, 38, 61],
  },
  {
    title: "Uptown Funk",
    artist: "Mark Ronson",
    genre: "Dance Pop",
    features: [115, 61, 86],
  },
  {
    title: "Take Me To Church",
    artist: "Hozier",
    genre: "irish singer-songwriter",
    features: [129, 66, 57],
  },
  {
    title: "Sugar",
    artist: "Maroon 5",
    genre: "Pop",
    features: [120, 79, 75],
  },
  {
    title: "Sorry",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [100, 76, 65],
  },
  {
    title: "FourFiveSeconds",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [206, 27, 58],
  },
  {
    title: '"Love Me Like You Do - From ""Fifty Shades Of Grey"""',
    artist: "Ellie Goulding",
    genre: "Dance Pop",
    features: [190, 61, 26],
  },
  {
    title:
      '"Earned It (Fifty Shades Of Grey) - From The ""Fifty Shades Of Grey"" Soundtrack"',
    artist: "The Weeknd",
    genre: "Canadian Contemporary R&B",
    features: [120, 38, 66],
  },
  {
    title: "What Do You Mean?",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [125, 57, 85],
  },
  {
    title: "Stitches",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [150, 75, 75],
  },
  {
    title: "Want to Want Me",
    artist: "Jason Derulo",
    genre: "Dance Pop",
    features: [114, 68, 78],
  },
  {
    title: "My House",
    artist: "Flo Rida",
    genre: "Dance Pop",
    features: [94, 70, 69],
  },
  {
    title: "Waves - Robin Schulz Radio Edit",
    artist: "Mr. Probz",
    genre: "Tropical House",
    features: [120, 51, 83],
  },
  {
    title: "Night Changes",
    artist: "One Direction",
    genre: "Boy Band",
    features: [120, 52, 67],
  },
  {
    title: "How Deep Is Your Love",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [122, 87, 74],
  },
  {
    title: "Never Forget You",
    artist: "Zara Larsson",
    genre: "Dance Pop",
    features: [146, 73, 58],
  },
  {
    title: "Love Me Harder",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [99, 71, 47],
  },
  {
    title: "Animals",
    artist: "Maroon 5",
    genre: "Pop",
    features: [190, 74, 28],
  },
  {
    title: "Blame",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [128, 86, 41],
  },
  {
    title: "Worth It",
    artist: "Fifth Harmony",
    genre: "Dance Pop",
    features: [100, 77, 88],
  },
  {
    title: "Break Free",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [130, 70, 69],
  },
  {
    title: "Don't",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [95, 61, 81],
  },
  {
    title: "Elastic Heart",
    artist: "Sia",
    genre: "Australian dance",
    features: [130, 79, 42],
  },
  {
    title: "Rather Be (feat. Jess Glynne)",
    artist: "Clean Bandit",
    genre: "Dance Pop",
    features: [121, 59, 80],
  },
  {
    title: "Hello",
    artist: "Adele",
    genre: "British Soul",
    features: [158, 45, 48],
  },
  {
    title: "Dear Future Husband",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [79, 78, 66],
  },
  {
    title: "43776",
    artist: "Beyonce",
    genre: "Dance Pop",
    features: [136, 71, 75],
  },
  {
    title: "The Heart Wants What It Wants",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [83, 79, 62],
  },
  {
    title: '"Hey Mama (feat. Nicki Minaj',
    artist: ' Bebe Rexha & Afrojack)"',
    genre: "David Guetta",
    features: [null, 86, 73],
  },
  {
    title: "Genie In a Bottle",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [176, 80, 63],
  },
  {
    title: "Company",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [95, 80, 59],
  },
  {
    title: "Sing",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [120, 67, 82],
  },
  {
    title: "Jealous - Remix",
    artist: "Nick Jonas",
    genre: "Dance Pop",
    features: [93, 71, 68],
  },
  {
    title: "Really Don't Care",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [121, 73, 71],
  },
  {
    title: '"Downtown (feat. Melle Mel',
    artist: " Grandmaster Caz",
    genre: ' Kool Moe Dee & Eric Nally)"',
    features: [null, null, 110],
  },
  {
    title: "Only Love Can Hurt Like This",
    artist: "Paloma Faith",
    genre: "British Soul",
    features: [91, 89, 57],
  },
  {
    title: "Heartbeat Song",
    artist: "Kelly Clarkson",
    genre: "Dance Pop",
    features: [149, 80, 49],
  },
  {
    title: "Up",
    artist: "Olly Murs",
    genre: "Dance Pop",
    features: [115, 85, 69],
  },
  {
    title: "Trumpets",
    artist: "Jason Derulo",
    genre: "Dance Pop",
    features: [82, 70, 63],
  },
  {
    title: "Runnin' (Lose It All)",
    artist: "Naughty Boy",
    genre: "Tropical House",
    features: [139, 85, 32],
  },
  {
    title: "Same Old Love",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [98, 59, 67],
  },
  {
    title: "I Want You To Know",
    artist: "Zedd",
    genre: "Complextro",
    features: [130, 85, 58],
  },
  {
    title: "Lips Are Movin",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [139, 83, 78],
  },
  {
    title: "I'll Show You",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [192, 61, 36],
  },
  {
    title: "Here",
    artist: "Alessia Cara",
    genre: "Canadian Contemporary R&B",
    features: [120, 82, 38],
  },
  {
    title: "I Lived",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [120, 85, 59],
  },
  {
    title: "Fireball (feat. John Ryan)",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [123, 94, 69],
  },
  {
    title: "Easy Love",
    artist: "Sigala",
    genre: "Dance Pop",
    features: [124, 94, 68],
  },
  {
    title: "The Feeling",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [127, 81, 53],
  },
  {
    title: "I Really Like You",
    artist: "Carly Rae Jepsen",
    genre: "Canadian Pop",
    features: [122, 81, 62],
  },
  {
    title: "BO$$",
    artist: "Fifth Harmony",
    genre: "Dance Pop",
    features: [103, 87, 81],
  },
  {
    title: "Sugar",
    artist: "Maroon 5",
    genre: "Pop",
    features: [120, 79, 75],
  },
  {
    title: "Focus",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [100, 88, 67],
  },
  {
    title: "All About That Bass",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [134, 88, 81],
  },
  {
    title: "On My Mind",
    artist: "Ellie Goulding",
    genre: "Dance Pop",
    features: [155, 71, 70],
  },
  {
    title: "Love Me Like You",
    artist: "Little Mix",
    genre: "Dance Pop",
    features: [106, 67, 79],
  },
  {
    title: "Broken Arrows",
    artist: "Avicii",
    genre: "Big Room",
    features: [116, 67, 63],
  },
  {
    title: "Booty",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [129, 95, 71],
  },
  {
    title: "What Do You Mean? - Acoustic",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [125, 36, 77],
  },
  {
    title: "Mark My Words",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [114, 26, 38],
  },
  {
    title: "Lay It All on Me",
    artist: "Rudimental",
    genre: "Dance Pop",
    features: [123, 75, 67],
  },
  {
    title: "American Oxygen",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [78, 75, 39],
  },
  {
    title: "Bang Bang",
    artist: "Jessie J",
    genre: "Australian Pop",
    features: [150, 75, 71],
  },
  {
    title: "Reality - Radio Edit",
    artist: "Lost Frequencies",
    genre: "Belgian EDM",
    features: [122, 70, 71],
  },
  {
    title: "Alive",
    artist: "Sia",
    genre: "Australian dance",
    features: [100, 76, 51],
  },
  {
    title: "Sugar (feat. Francesco Yates)",
    artist: "Robin Schulz",
    genre: "Dance Pop",
    features: [123, 82, 64],
  },
  {
    title: "Been You",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [113, 78, 74],
  },
  {
    title: "Prayer in C - Robin Schulz Radio Edit",
    artist: "Lilly Wood and The Prick",
    genre: "French Indie Pop",
    features: [123, 89, 76],
  },
  {
    title: "See You Again (feat. Charlie Puth)",
    artist: "Wiz Khalifa",
    genre: "Hip Hop",
    features: [80, 48, 69],
  },
  {
    title: "Heroes (we could be)",
    artist: "Alesso",
    genre: "Big Room",
    features: [126, 75, 52],
  },
  {
    title: '"Feel The Light - From The ""Home"" Soundtrack"',
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [156, 60, 47],
  },
  {
    title: "Perfect",
    artist: "One Direction",
    genre: "Boy Band",
    features: [100, 82, 65],
  },
  {
    title: "Ghosttown",
    artist: "Madonna",
    genre: "Dance Pop",
    features: [79, 55, 54],
  },
  {
    title: "Bang My Head (feat. Sia & Fetty Wap)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [108, 87, 60],
  },
  {
    title: "Bloodstream",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [89, 59, 48],
  },
  {
    title: "Living For Love",
    artist: "Madonna",
    genre: "Dance Pop",
    features: [123, 79, 67],
  },
  {
    title: "Baby Don't Lie",
    artist: "Gwen Stefani",
    genre: "Dance Pop",
    features: [100, 55, 69],
  },
  {
    title: "Don't Be so Hard on Yourself",
    artist: "Jess Glynne",
    genre: "Dance Pop",
    features: [120, 82, 57],
  },
  {
    title: "Steal My Girl",
    artist: "One Direction",
    genre: "Boy Band",
    features: [77, 76, 47],
  },
  {
    title:
      '"Celebrate (From the Original Motion Picture ""Penguins of Madagascar"")"',
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [127, 85, 68],
  },
  {
    title: "We Are Here",
    artist: "Alicia Keys",
    genre: "Hip Pop",
    features: [93, 67, 64],
  },
  {
    title: "St Jude",
    artist: "Florence + The Machine",
    genre: "Art Pop",
    features: [117, 43, 26],
  },
  {
    title: "Yesterday (feat. Bebe Rexha)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [128, 78, 57],
  },
  {
    title: "Time of Our Lives",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [124, 80, 72],
  },
  {
    title: "Sparks",
    artist: "Hilary Duff",
    genre: "Dance Pop",
    features: [122, 88, 85],
  },
  {
    title: "Mr. Put It Down",
    artist: "Ricky Martin",
    genre: "Dance Pop",
    features: [128, 78, 80],
  },
  {
    title: "Legendary Lovers",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [126, 84, 62],
  },
  {
    title: "Spark The Fire",
    artist: "Gwen Stefani",
    genre: "Dance Pop",
    features: [120, 80, 88],
  },
  {
    title: "Run Run Run",
    artist: "Kelly Clarkson",
    genre: "Dance Pop",
    features: [112, 37, 28],
  },
  {
    title: "Let Me Be Your Lover",
    artist: "Enrique Iglesias",
    genre: "Dance Pop",
    features: [112, 90, 72],
  },
  {
    title: "Dangerous",
    artist: "Jennifer Hudson",
    genre: "Dance Pop",
    features: [109, 53, 90],
  },
  {
    title: "L.A.LOVE (la la)",
    artist: "Fergie",
    genre: "Dance Pop",
    features: [202, 39, 48],
  },
  {
    title: "The Hills",
    artist: "The Weeknd",
    genre: "Canadian Contemporary R&B",
    features: [113, 56, 58],
  },
  {
    title: "Love Yourself",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [100, 38, 61],
  },
  {
    title: "Cake By The Ocean",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [119, 75, 77],
  },
  {
    title: "Don't Let Me Down",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [160, 87, 53],
  },
  {
    title: "In the Name of Love",
    artist: "Martin Garrix",
    genre: "Big Room",
    features: [134, 52, 50],
  },
  {
    title: "Into You",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [108, 73, 62],
  },
  {
    title: "This Is What You Came For",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [124, 93, 63],
  },
  {
    title: "Million Reasons",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [130, 42, 67],
  },
  {
    title: "Needed Me",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [111, 31, 67],
  },
  {
    title: "7 Years",
    artist: "Lukas Graham",
    genre: "danish Pop",
    features: [120, 47, 77],
  },
  {
    title:
      '"CAN\'T STOP THE FEELING! (Original Song from DreamWorks Animation\'s ""TROLLS"")"',
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [113, 83, 67],
  },
  {
    title: "Work from Home (feat. Ty Dolla $ign)",
    artist: "Fifth Harmony",
    genre: "Dance Pop",
    features: [105, 59, 80],
  },
  {
    title: "Scars To Your Beautiful",
    artist: "Alessia Cara",
    genre: "Canadian Contemporary R&B",
    features: [97, 74, 57],
  },
  {
    title: "Like I'm Gonna Lose You (feat. John Legend)",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [108, 53, 63],
  },
  {
    title: "Work",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [92, 53, 73],
  },
  {
    title: "Stitches",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [150, 75, 75],
  },
  {
    title: '"Me',
    artist: ' Myself & I"',
    genre: "G-Eazy",
    features: [null, 112, 67],
  },
  {
    title: "I Took A Pill In Ibiza - Seeb Remix",
    artist: "Mike Posner",
    genre: "Dance Pop",
    features: [102, 71, 66],
  },
  {
    title: "Dangerous Woman",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [134, 60, 66],
  },
  {
    title: "Starving",
    artist: "Hailee Steinfeld",
    genre: "Dance Pop",
    features: [100, 62, 73],
  },
  {
    title: "Shout Out to My Ex",
    artist: "Little Mix",
    genre: "Dance Pop",
    features: [126, 75, 77],
  },
  {
    title: "Electric Love",
    artist: "B0NS",
    genre: "Electropop",
    features: [120, 80, 61],
  },
  {
    title: "Confident",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [130, 75, 59],
  },
  {
    title: "Too Good",
    artist: "Drake",
    genre: "Canadian Hip Hop",
    features: [118, 65, 79],
  },
  {
    title: "Roses",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [100, 80, 71],
  },
  {
    title: "Cold Water (feat. Justin Bieber & M?",
    artist: "Major Lazer)",
    genre: "Dance Pop",
    features: [93, 80, 61],
  },
  {
    title: "Me Too",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [124, 69, 93],
  },
  {
    title: "Light It Up (feat. Nyla & Fuse ODG) [Remix]",
    artist: "Major Lazer",
    genre: "Dance Pop",
    features: [108, 88, 75],
  },
  {
    title: "Ain't Your Mama",
    artist: "Jennifer Lopez",
    genre: "Dance Pop",
    features: [120, 68, 76],
  },
  {
    title: "Close",
    artist: "Nick Jonas",
    genre: "Dance Pop",
    features: [124, 62, 65],
  },
  {
    title: "Toothbrush",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [105, 79, 55],
  },
  {
    title: "All We Know",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [90, 59, 66],
  },
  {
    title: "Final Song",
    artist: "M0",
    genre: "Dance Pop",
    features: [105, 67, 70],
  },
  {
    title: "Company",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [95, 80, 59],
  },
  {
    title: "Hands To Myself",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [111, 50, 81],
  },
  {
    title: "All I Ask",
    artist: "Adele",
    genre: "British Soul",
    features: [142, 28, 59],
  },
  {
    title:
      '"Just Like Fire (From the Original Motion Picture ""Alice Through The Looking Glass"")"',
    artist: "P!nk",
    genre: "Dance Pop",
    features: [163, 70, 63],
  },
  {
    title: "NO",
    artist: "Meghan Trainor",
    genre: "Dance Pop",
    features: [92, 80, 56],
  },
  {
    title: "Kill Em With Kindness",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [120, 88, 76],
  },
  {
    title: "Cool Girl",
    artist: "Tove Lo",
    genre: "Dance Pop",
    features: [102, 69, 67],
  },
  {
    title: "Runnin' (Lose It All)",
    artist: "Naughty Boy",
    genre: "Tropical House",
    features: [139, 85, 32],
  },
  {
    title: "Here",
    artist: "Alessia Cara",
    genre: "Canadian Contemporary R&B",
    features: [120, 82, 38],
  },
  {
    title: "Perfect Illusion",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [125, 86, 61],
  },
  {
    title: "PILLOWTALK",
    artist: "ZAYN",
    genre: "Dance Pop",
    features: [125, 70, 59],
  },
  {
    title: "Out Of The Woods",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [92, 84, 55],
  },
  {
    title: "Rise",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [101, 64, 55],
  },
  {
    title: "Wherever I Go",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [100, 69, 55],
  },
  {
    title: "Body Say",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [87, 74, 63],
  },
  {
    title: "Don't Be A Fool",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [175, 34, 47],
  },
  {
    title: "LIKE I WOULD",
    artist: "ZAYN",
    genre: "Dance Pop",
    features: [113, 83, 56],
  },
  {
    title: "Cheap Thrills",
    artist: "Sia",
    genre: "Australian dance",
    features: [90, 80, 59],
  },
  {
    title: "I Got You",
    artist: "Bebe Rexha",
    genre: "Dance Pop",
    features: [98, 89, 61],
  },
  {
    title: "Run Away With Me",
    artist: "Carly Rae Jepsen",
    genre: "Canadian Pop",
    features: [119, 72, 56],
  },
  {
    title: "Cruel (feat. ZAYN)",
    artist: "Snakehips",
    genre: "Dance Pop",
    features: [110, 88, 60],
  },
  {
    title: "Send My Love (To Your New Lover)",
    artist: "Adele",
    genre: "British Soul",
    features: [164, 52, 69],
  },
  {
    title: "WTF (Where They From)",
    artist: "Missy Elliott",
    genre: "Dance Pop",
    features: [120, 82, 93],
  },
  {
    title: "Desire",
    artist: "Years & Years",
    genre: "Dance Pop",
    features: [126, 78, 71],
  },
  {
    title: "When We Were Young",
    artist: "Adele",
    genre: "British Soul",
    features: [144, 59, 38],
  },
  {
    title: "I Know What You Did Last Summer",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [114, 77, 68],
  },
  {
    title:
      "Wish That You Were Here - From 揗iss Peregrine抯 Home for Peculiar Children?Original Motion Picture",
    artist: "Florence + The Machine",
    genre: "Art Pop",
    features: [94, 57, 37],
  },
  {
    title: "Hurts",
    artist: "Emeli Sande",
    genre: "Dance Pop",
    features: [106, 64, 58],
  },
  {
    title: "Change",
    artist: "Christina Aguilera",
    genre: "Dance Pop",
    features: [82, 54, 62],
  },
  {
    title: "Make Me... (feat. G-Eazy)",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [123, 70, 70],
  },
  {
    title: "Keeping Your Head Up",
    artist: "Birdy",
    genre: "Neo Mellow",
    features: [122, 78, 60],
  },
  {
    title: "True Colors",
    artist: "Zedd",
    genre: "Complextro",
    features: [126, 79, 57],
  },
  {
    title: "Make Me Like You",
    artist: "Gwen Stefani",
    genre: "Dance Pop",
    features: [118, 71, 74],
  },
  {
    title: "Champagne Problems",
    artist: "Nick Jonas",
    genre: "Dance Pop",
    features: [108, 78, 73],
  },
  {
    title: "Blown",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [130, 95, 63],
  },
  {
    title: "Start",
    artist: "John Legend",
    genre: "Neo Mellow",
    features: [110, 4, 52],
  },
  {
    title: "Pep Rally",
    artist: "Missy Elliott",
    genre: "Dance Pop",
    features: [90, 75, 83],
  },
  {
    title: "Higher",
    artist: "Carly Rae Jepsen",
    genre: "Canadian Pop",
    features: [114, 87, 65],
  },
  {
    title: "Invitation",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [112, 65, 37],
  },
  {
    title: "One Call Away (feat. Tyga) - Remix",
    artist: "Charlie Puth",
    genre: "Dance Pop",
    features: [91, 69, 75],
  },
  {
    title: "Beautiful Birds (feat. Birdy)",
    artist: "Passenger",
    genre: "Folk-Pop",
    features: [86, 17, 39],
  },
  {
    title: "Little Lies",
    artist: "Hilary Duff",
    genre: "Dance Pop",
    features: [124, 76, 57],
  },
  {
    title: "Do You Wanna Come Over?",
    artist: "Britney Spears",
    genre: "Dance Pop",
    features: [121, 70, 75],
  },
  {
    title: "BURNITUP!",
    artist: "Janet Jackson",
    genre: "Dance Pop",
    features: [123, 71, 83],
  },
  {
    title: "Picky - Remix",
    artist: "Joey Montana",
    genre: "Latin",
    features: [186, 81, 70],
  },
  {
    title: "Behind Your Back",
    artist: "Nelly Furtado",
    genre: "Canadian Latin",
    features: [98, 47, 80],
  },
  {
    title: "Million Years Ago",
    artist: "Adele",
    genre: "British Soul",
    features: [0, 0, 0],
  },
  {
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [96, 65, 83],
  },
  {
    title: "Closer",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [95, 52, 75],
  },
  {
    title: "Starboy",
    artist: "The Weeknd",
    genre: "Canadian Contemporary R&B",
    features: [186, 59, 68],
  },
  {
    title: "Treat You Better",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [83, 82, 44],
  },
  {
    title: "That's What I Like",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [134, 56, 85],
  },
  {
    title: "Let Me Love You",
    artist: "DJ Snake",
    genre: "Electronic Trap",
    features: [100, 72, 65],
  },
  {
    title: "I Feel It Coming",
    artist: "The Weeknd",
    genre: "Canadian Contemporary R&B",
    features: [93, 82, 77],
  },
  {
    title: "Mercy",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [148, 66, 56],
  },
  {
    title: "Side To Side",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [159, 74, 65],
  },
  {
    title: "Stay",
    artist: "Zedd",
    genre: "Complextro",
    features: [102, 62, 69],
  },
  {
    title: "It Ain't Me (with Selena Gomez)",
    artist: "Kygo",
    genre: "EDM",
    features: [100, 53, 64],
  },
  {
    title: "Malibu",
    artist: "Miley Cyrus",
    genre: "Dance Pop",
    features: [140, 78, 57],
  },
  {
    title: "Something Just Like This",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [103, 65, 61],
  },
  {
    title: "Rockabye (feat. Sean Paul & Anne-Marie)",
    artist: "Clean Bandit",
    genre: "Dance Pop",
    features: [102, 76, 72],
  },
  {
    title: "I Don抰 Wanna Live Forever (Fifty Shades Darker)",
    artist: "ZAYN",
    genre: "Dance Pop",
    features: [118, 45, 74],
  },
  {
    title: "My Way",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [120, 91, 82],
  },
  {
    title: "Praying",
    artist: "Kesha",
    genre: "Dance Pop",
    features: [73, 39, 58],
  },
  {
    title: "Despacito - Remix",
    artist: "Luis Fonsi",
    genre: "Latin",
    features: [178, 82, 65],
  },
  {
    title: "The Greatest",
    artist: "Sia",
    genre: "Australian dance",
    features: [192, 73, 67],
  },
  {
    title: "There for You",
    artist: "Martin Garrix",
    genre: "Big Room",
    features: [106, 64, 61],
  },
  {
    title: "Paris",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [100, 64, 65],
  },
  {
    title: "Crying in the Club",
    artist: "Camila Cabello",
    genre: "Dance Pop",
    features: [85, 62, 33],
  },
  {
    title: "Mama",
    artist: "Jonas Blue",
    genre: "Dance Pop",
    features: [104, 79, 74],
  },
  {
    title: "Slide (feat. Frank Ocean & Migos)",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [104, 80, 74],
  },
  {
    title: "Swish Swish",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [120, 71, 84],
  },
  {
    title: "Chained To The Rhythm",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [190, 80, 45],
  },
  {
    title: "Cold (feat. Future)",
    artist: "Maroon 5",
    genre: "Pop",
    features: [100, 72, 69],
  },
  {
    title: "Love",
    artist: "Lana Del Rey",
    genre: "Art Pop",
    features: [99, 37, 53],
  },
  {
    title: "Reggaet髇 Lento (Remix)",
    artist: "CNCO",
    genre: "Boy Band",
    features: [94, 91, 53],
  },
  {
    title: "All I Ask",
    artist: "Adele",
    genre: "British Soul",
    features: [142, 28, 59],
  },
  {
    title: "First Time",
    artist: "Kygo",
    genre: "EDM",
    features: [90, 59, 63],
  },
  {
    title: "The Cure",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [100, 51, 70],
  },
  {
    title: '"How Far I\'ll Go - From ""Moana"""',
    artist: "Alessia Cara",
    genre: "Canadian Contemporary R&B",
    features: [181, 54, 31],
  },
  {
    title: "Bodak Yellow",
    artist: "Cardi B",
    genre: "Pop",
    features: [125, 72, 93],
  },
  {
    title: "Rich Love (with Seeb)",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [105, 87, 40],
  },
  {
    title: "Tired",
    artist: "Alan Walker",
    genre: "Electro house",
    features: [124, 88, 69],
  },
  {
    title: "Came Here for Love",
    artist: "Sigala",
    genre: "Dance Pop",
    features: [125, 87, 71],
  },
  {
    title: "24K Magic",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [107, 80, 82],
  },
  {
    title: "Strip That Down (feat. Quavo)",
    artist: "Liam Payne",
    genre: "Dance Pop",
    features: [106, 50, 87],
  },
  {
    title: "Cut To The Feeling",
    artist: "Carly Rae Jepsen",
    genre: "Canadian Pop",
    features: [115, 91, 71],
  },
  {
    title: "OK - Spotify Version",
    artist: "Robin Schulz",
    genre: "Dance Pop",
    features: [122, 81, 65],
  },
  {
    title: "Bon app閠it",
    artist: "Katy Perry",
    genre: "Dance Pop",
    features: [106, 79, 80],
  },
  {
    title: "Summer Bummer (feat. A$AP Rocky & Playboi Carti)",
    artist: "Lana Del Rey",
    genre: "Art Pop",
    features: [135, 57, 76],
  },
  {
    title: "Get Low (with Liam Payne)",
    artist: "Zedd",
    genre: "Complextro",
    features: [108, 93, 72],
  },
  {
    title: "Kissing Strangers",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [120, 74, 77],
  },
  {
    title: "Slow Hands",
    artist: "Niall Horan",
    genre: "Dance Pop",
    features: [86, 42, 74],
  },
  {
    title: "Younger Now",
    artist: "Miley Cyrus",
    genre: "Dance Pop",
    features: [122, 87, 55],
  },
  {
    title: "Body Moves",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [102, 69, 65],
  },
  {
    title: "Reality (feat. Janieck Devy) - Radio Edit",
    artist: "Lost Frequencies",
    genre: "Belgian EDM",
    features: [122, 64, 73],
  },
  {
    title: "Angel",
    artist: "Fifth Harmony",
    genre: "Dance Pop",
    features: [124, 53, 74],
  },
  {
    title: "Touch (feat. Kid Ink)",
    artist: "Little Mix",
    genre: "Dance Pop",
    features: [102, 75, 64],
  },
  {
    title: "We Don't Talk Anymore - DROELOE Remix",
    artist: "Charlie Puth",
    genre: "Dance Pop",
    features: [100, 82, 70],
  },
  {
    title: "Love Incredible (feat. Camila Cabello)",
    artist: "Cashmere Cat",
    genre: "Downtempo",
    features: [167, 50, 37],
  },
  {
    title: "No Vacancy (with Sebasti醤 Yatra)",
    artist: "OneRepublic",
    genre: "Dance Pop",
    features: [100, 76, 69],
  },
  {
    title: "Rich Boy",
    artist: "Galantis",
    genre: "Big Room",
    features: [110, 90, 74],
  },
  {
    title: "Lust for Life (with The Weeknd)",
    artist: "Lana Del Rey",
    genre: "Art Pop",
    features: [100, 67, 51],
  },
  {
    title: "Greenlight (feat. Flo Rida & LunchMoney Lewis)",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [115, 83, 70],
  },
  {
    title: "Influence",
    artist: "Tove Lo",
    genre: "Dance Pop",
    features: [105, 59, 77],
  },
  {
    title: "Remember I Told You",
    artist: "Nick Jonas",
    genre: "Dance Pop",
    features: [113, 53, 68],
  },
  {
    title: "Messin' Around",
    artist: "Pitbull",
    genre: "Dance Pop",
    features: [158, 81, 57],
  },
  {
    title: "Water Under the Bridge",
    artist: "Adele",
    genre: "British Soul",
    features: [95, 84, 60],
  },
  {
    title: "Free Me",
    artist: "Sia",
    genre: "Australian dance",
    features: [87, 46, 27],
  },
  {
    title: "Kissing Strangers - Remix",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [120, 77, 76],
  },
  {
    title: "A L I E N S",
    artist: "Coldplay",
    genre: "permanent wave",
    features: [148, 88, 43],
  },
  {
    title: "One Kiss (with Dua Lipa)",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [124, 86, 79],
  },
  {
    title: "Havana (feat. Young Thug)",
    artist: "Camila Cabello",
    genre: "Dance Pop",
    features: [105, 52, 77],
  },
  {
    title: "I Like It",
    artist: "Cardi B",
    genre: "Pop",
    features: [136, 73, 82],
  },
  {
    title: "New Rules",
    artist: "Dua Lipa",
    genre: "Dance Pop",
    features: [116, 70, 76],
  },
  {
    title: "There's Nothing Holdin' Me Back",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [122, 81, 87],
  },
  {
    title: "no tears left to cry",
    artist: "Ariana Grande",
    genre: "Dance Pop",
    features: [122, 71, 70],
  },
  {
    title: "IDGAF",
    artist: "Dua Lipa",
    genre: "Dance Pop",
    features: [97, 54, 84],
  },
  {
    title: "In My Blood",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [140, 71, 62],
  },
  {
    title: "Wolves",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [125, 80, 72],
  },
  {
    title: "Dusk Till Dawn - Radio Edit",
    artist: "ZAYN",
    genre: "Dance Pop",
    features: [180, 44, 26],
  },
  {
    title: "Attention",
    artist: "Charlie Puth",
    genre: "Dance Pop",
    features: [100, 61, 78],
  },
  {
    title: "Electricity (with Dua Lipa)",
    artist: "Silk City",
    genre: "EDM",
    features: [118, 67, 59],
  },
  {
    title: "Love On The Brain",
    artist: "Rihanna",
    genre: "Barbadian Pop",
    features: [172, 64, 51],
  },
  {
    title: '"Let Me Go (with Alesso',
    artist: ' Florida Georgia Line & watt)"',
    genre: "Hailee Steinfeld",
    features: [null, 103, 71],
  },
  {
    title: "Silence",
    artist: "Marshmello",
    genre: "brostep",
    features: [142, 76, 52],
  },
  {
    title: "Sorry Not Sorry",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [144, 64, 71],
  },
  {
    title: "Shallow - Radio Edit",
    artist: "Lady Gaga",
    genre: "Dance Pop",
    features: [96, 33, 57],
  },
  {
    title: "These Days",
    artist: "Rudimental",
    genre: "Dance Pop",
    features: [92, 81, 65],
  },
  {
    title: "What Lovers Do (feat. SZA)",
    artist: "Maroon 5",
    genre: "Pop",
    features: [110, 60, 80],
  },
  {
    title: "Finesse - Remix; feat. Cardi B",
    artist: "Bruno Mars",
    genre: "Pop",
    features: [105, 86, 70],
  },
  {
    title: "Perfect Duet Ed Sheeran & Beyonce",
    artist: "Pop",
    genre: "95",
    features: [30, 59, null],
  },
  {
    title: "Bad At Love",
    artist: "Halsey",
    genre: "Dance Pop",
    features: [118, 75, 68],
  },
  {
    title: "Him & I with Halsey",
    artist: "G-Eazy",
    genre: "Hip Hop",
    features: [88, 73, 59],
  },
  {
    title: "Friends with BloodPope",
    artist: "Justin Bieber",
    genre: "Canadian Pop",
    features: [105, 73, 74],
  },
  {
    title: "Wild Thoughts (feat. Rihanna & Bryson Tiller)",
    artist: "DJ Khaled",
    genre: "Dance Pop",
    features: [98, 67, 67],
  },
  {
    title: "My My My!",
    artist: "Troye Sivan",
    genre: "Dance Pop",
    features: [103, 46, 70],
  },
  {
    title: "Capital Letters",
    artist: "Hailee Steinfeld",
    genre: "Dance Pop",
    features: [100, 81, 66],
  },
  {
    title: "Sick Boy",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [90, 58, 66],
  },
  {
    title: "Tequila",
    artist: "Dan + Shay",
    genre: "contemporary country",
    features: [86, 59, 47],
  },
  {
    title: "Look What You Made Me Do",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [128, 71, 77],
  },
  {
    title: "Youth (feat. Khalid)",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [100, 60, 53],
  },
  {
    title: "Bad Liar",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [121, 41, 97],
  },
  {
    title: "Anywhere",
    artist: "Rita Ora",
    genre: "Dance Pop",
    features: [107, 80, 63],
  },
  {
    title: "Say Something",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [97, 63, 71],
  },
  {
    title: "Chun-Li",
    artist: "Nicki Minaj",
    genre: "Dance Pop",
    features: [129, 73, 69],
  },
  {
    title: "Sign of the Times",
    artist: "Harry Styles",
    genre: "Dance Pop",
    features: [120, 57, 52],
  },
  {
    title: "Familiar",
    artist: "Liam Payne",
    genre: "Dance Pop",
    features: [93, 81, 64],
  },
  {
    title: "Let Me",
    artist: "ZAYN",
    genre: "Dance Pop",
    features: [168, 57, 46],
  },
  {
    title: "Supernova",
    artist: "Ansel Elgort",
    genre: "Dance Pop",
    features: [140, 62, 77],
  },
  {
    title: "Nervous",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [122, 62, 84],
  },
  {
    title: "First Time",
    artist: "Kygo",
    genre: "EDM",
    features: [90, 59, 63],
  },
  {
    title: "End Game",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [159, 59, 65],
  },
  {
    title: "Mi Gente feat. Beyonce",
    artist: "J Balvin",
    genre: "Latin",
    features: [105, 72, 76],
  },
  {
    title: "Lemon",
    artist: "N.E.R.D",
    genre: "Hip Hop",
    features: [95, 73, 92],
  },
  {
    title: "For You (With Rita Ora)",
    artist: "Liam Payne",
    genre: "Dance Pop",
    features: [113, 80, 54],
  },
  {
    title: "Want To",
    artist: "Dua Lipa",
    genre: "Dance Pop",
    features: [92, 69, 57],
  },
  {
    title: "What I Need (feat. Kehlani)",
    artist: "Hayley Kiyoko",
    genre: "Dance Pop",
    features: [104, 79, 63],
  },
  {
    title: "Wait",
    artist: "Maroon 5",
    genre: "Pop",
    features: [126, 60, 66],
  },
  {
    title: "What About Us",
    artist: "P!nk",
    genre: "Dance Pop",
    features: [114, 59, 39],
  },
  {
    title: "Kissing Strangers",
    artist: "DNCE",
    genre: "Dance Pop",
    features: [120, 74, 77],
  },
  {
    title: "2U (feat. Justin Bieber)",
    artist: "David Guetta",
    genre: "Dance Pop",
    features: [145, 61, 53],
  },
  {
    title: "Walk On Water feat. Beyonc?",
    artist: "Eminem",
    genre: "Detroit Hip Hop",
    features: [82, 44, 48],
  },
  {
    title: "This Town",
    artist: "Niall Horan",
    genre: "Dance Pop",
    features: [112, 41, 68],
  },
  {
    title: '"Girls (feat. Cardi B',
    artist: ' Bebe Rexha & Charli XCX)"',
    genre: "Rita Ora",
    features: [null, 94, 69],
  },
  {
    title: "MOVE TO MIAMI",
    artist: "Enrique Iglesias",
    genre: "Dance Pop",
    features: [100, 87, 76],
  },
  {
    title: "Miss You (with Major Lazer & Tory Lanez)",
    artist: "Cashmere Cat",
    genre: "Downtempo",
    features: [100, 64, 75],
  },
  {
    title: "Filthy",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [97, 58, 75],
  },
  {
    title: "Never Be the Same - Radio Edit",
    artist: "Camila Cabello",
    genre: "Dance Pop",
    features: [130, 69, 63],
  },
  {
    title: "Ferrari",
    artist: "Bebe Rexha",
    genre: "Dance Pop",
    features: [77, 48, 58],
  },
  {
    title: "Supplies",
    artist: "Justin Timberlake",
    genre: "Dance Pop",
    features: [120, 55, 79],
  },
  {
    title: "Boom Boom",
    artist: "RedOne",
    genre: "moroccan Pop",
    features: [110, 76, 75],
  },
  {
    title: "...Ready For It? - BloodPop?Remix",
    artist: "Taylor Swift",
    genre: "Pop",
    features: [160, 84, 58],
  },
  {
    title: "Drip (feat. Migos)",
    artist: "Cardi B",
    genre: "Pop",
    features: [130, 59, 97],
  },
  {
    title: "Tell Me You Love Me - NOTD Remix",
    artist: "Demi Lovato",
    genre: "Dance Pop",
    features: [102, 77, 58],
  },
  {
    title: "Memories",
    artist: "Maroon 5",
    genre: "Pop",
    features: [91, 32, 76],
  },
  {
    title: "Lose You To Love Me",
    artist: "Selena Gomez",
    genre: "Dance Pop",
    features: [102, 34, 51],
  },
  {
    title: "Someone You Loved",
    artist: "Lewis Capaldi",
    genre: "Pop",
    features: [110, 41, 50],
  },
  {
    title: "Se駉rita",
    artist: "Shawn Mendes",
    genre: "Canadian Pop",
    features: [117, 54, 76],
  },
  {
    title: "How Do You Sleep?",
    artist: "Sam Smith",
    genre: "Pop",
    features: [111, 68, 48],
  },
  {
    title: "South of the Border (feat. Camila Cabello & Cardi B)",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [98, 62, 86],
  },
  {
    title: "Trampoline (with ZAYN)",
    artist: "SHAED",
    genre: "Electropop",
    features: [127, 46, 62],
  },
  {
    title: "Happier",
    artist: "Marshmello",
    genre: "brostep",
    features: [100, 79, 69],
  },
  {
    title: "Truth Hurts",
    artist: "Lizzo",
    genre: "escape room",
    features: [158, 62, 72],
  },
  {
    title: "Good as Hell (feat. Ariana Grande) - Remix",
    artist: "Lizzo",
    genre: "escape room",
    features: [96, 89, 67],
  },
  {
    title: "Higher Love",
    artist: "Kygo",
    genre: "EDM",
    features: [104, 68, 69],
  },
  {
    title: "Only Human",
    artist: "Jonas Brothers",
    genre: "Boy Band",
    features: [94, 50, 80],
  },
  {
    title: "Beautiful People (feat. Khalid)",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [93, 65, 64],
  },
  {
    title: "Sucker",
    artist: "Jonas Brothers",
    genre: "Boy Band",
    features: [138, 73, 84],
  },
  {
    title: "Don't Call Me Up",
    artist: "Mabel",
    genre: "Dance Pop",
    features: [99, 88, 67],
  },
  {
    title: "I Don't Care (with Justin Bieber)",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [102, 68, 80],
  },
  {
    title: "Talk (feat. Disclosure)",
    artist: "Khalid",
    genre: "alternative r&b",
    features: [136, 40, 90],
  },
  {
    title: "Giant (with Rag'n'Bone Man)",
    artist: "Calvin Harris",
    genre: "Dance Pop",
    features: [122, 89, 81],
  },
  {
    title: "Takeaway",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [100, 51, 53],
  },
  {
    title: "All Around The World (La La La)",
    artist: "R3HAB",
    genre: "Big Room",
    features: [125, 86, 73],
  },
  {
    title: "Girls Like You (feat. Cardi B)",
    artist: "Maroon 5",
    genre: "Pop",
    features: [125, 54, 85],
  },
  {
    title: "Call You Mine",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [104, 70, 59],
  },
  {
    title: "No Guidance (feat. Drake)",
    artist: "Chris Brown",
    genre: "Dance Pop",
    features: [93, 45, 70],
  },
  {
    title: "Antisocial (with Travis Scott)",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [152, 82, 72],
  },
  {
    title: "Taki Taki (feat. Selena Gomez",
    artist: ' Ozuna & Cardi B)"',
    genre: "DJ Snake",
    features: [null, 96, 80],
  },
  {
    title: "Con Calma - Remix",
    artist: "Daddy Yankee",
    genre: "Latin",
    features: [94, 87, 74],
  },
  {
    title: "Find U Again (feat. Camila Cabello)",
    artist: "Mark Ronson",
    genre: "Dance Pop",
    features: [104, 66, 61],
  },
  {
    title: "Cross Me (feat. Chance the Rapper & PnB Rock)",
    artist: "Ed Sheeran",
    genre: "Pop",
    features: [95, 79, 75],
  },
  {
    title: '"No Brainer (feat. Justin Bieber',
    artist: ' Chance the Rapper & Quavo)"',
    genre: "DJ Khaled",
    features: [null, 136, 76],
  },
  {
    title: "Nothing Breaks Like a Heart (feat. Miley Cyrus)",
    artist: "Mark Ronson",
    genre: "Dance Pop",
    features: [114, 79, 60],
  },
  {
    title: "Kills You Slowly",
    artist: "The Chainsmokers",
    genre: "Electropop",
    features: [150, 44, 70],
  },
];
